name: 'Frontend'

on:
  push:
    branches: [ main ]
    paths:
      - frontend/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Connect to dockerhub
      run: docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: cd frontend && docker build . -t ${{secrets.DOCKER_LOGIN}}/gdp2024-frontend --output type=registry