name: 'Instance'

on:
  push:
    branches: [ main ]
    paths:
      - instance/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Connect to dockerhub
      run: docker login -u ${{secrets.DOCKER_LOGIN}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build . --file instance/Dockerfile -t ${{secrets.DOCKER_LOGIN}}/gdp2024-instance --output type=registry